version: 0.0.{build}
image:
  - Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
test: off
build_script:
  - ps: .\build.ps1 -Target Setup
  - ps: .\build.ps1 -Target Build
  - ps: .\build.ps1 -Target Package
artifacts:
  - path: .packaging\*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: h+Kd8nY2XH+VC12mQgL2Bs7YpgEdXYmY5eY9jnJLhVIXnsK5xsh2DyFtmsnK3m0L
  artifact: /.*\.nupkg/
environment:
  nuget_key:
    secure: h+Kd8nY2XH+VC12mQgL2Bs7YpgEdXYmY5eY9jnJLhVIXnsK5xsh2DyFtmsnK3m0L
