version: 0.1.{build}
test: off
build_script:
    - ps: .\build.ps1
artifacts:
    - path: packaging\*.nupkg
deploy:
    provider: NuGet
    api_key:
        secure: jIk7hDIpgOtyTG6FPxA3s55xN1pxaiJIBTeJrGlV664POb4pGAVdr90zFLt3jmDy
    artifact: /.*\.nupkg/
environment:
    nuget_key:
        secure: jIk7hDIpgOtyTG6FPxA3s55xN1pxaiJIBTeJrGlV664POb4pGAVdr90zFLt3jmDy
after_deploy:
    - ps: .\postDeploy.ps1