version: 0.0.{build}
image:
  - Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
test: off
build_script:
  - ps: .\build.ps1 -Target Setup
  - ps: .\build.ps1 -Target Build
  - ps: .\build.ps1 -Target Package
artifacts:
  - path: .packaging\*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: ub5fXqjgRwLxbqwd8dulJcq40yk9Lw39ZkmTwb6ZZf8I7FThhU9dweBjIRqvQs6q
  artifact: /.*\.nupkg/
environment:
  nuget_key:
    secure: ub5fXqjgRwLxbqwd8dulJcq40yk9Lw39ZkmTwb6ZZf8I7FThhU9dweBjIRqvQs6q
